name: Despliegue de API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Instalar dependencias
        run: yarn install --frozen-lockfile

      - name: Construir imagen de Docker
        run: docker build -t my-api .

      - name: Iniciar contenedor de Docker
        run: |
          docker run -d -p 8080:8080 \
          --name onetournament \
          --env-file .env \
          erikpc/onetournament
